### ISSUE TITLE
[possible false positive] stack buffer underflow in factor::factor_vm::slot_visitor

### ISSUE THREAD

**Issue by catb0t** [factor/factor#1923]
the other errors i've been posting are "minor" UB and nonfatal. the following error is considered fatal by ASan. (but see  https://github.com/google/sanitizers/issues/189)

the backtrace is
```
==17259==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7fff952b3000; bottom 0x7ffaf54fb000; size: 0x00049fdb8000 (19861831680)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
=================================================================
==17259==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7ffaf54fce70 at pc 0x557878a4b31d bp 0x7ffaf54fcd60 sp 0x7ffaf54fcd50
WRITE of size 8 at 0x7ffaf54fce70 thread T0
    #0 0x557878a4b31c in factor::slot_visitor<factor::from_tenured_refs_copier>::slot_visitor(factor::factor_vm*, factor::from_tenured_refs_copier) vm/slot_visitor.hpp:130
    #1 0x557878a47641 in factor::factor_vm::collect_aging() vm/aging_collector.cpp:47
    #2 0x557878afbda9 in factor::factor_vm::gc(factor::gc_op, unsigned long) vm/gc.cpp:95
    #3 0x557878afc802 in factor::factor_vm::primitive_minor_gc() vm/gc.cpp:149
    #4 0x557878a66007 in factor::factor_vm::allot_object(unsigned long, unsigned long) vm/allot.hpp:75
    #5 0x557878b47d49 in factor::tuple* factor::factor_vm::allot<factor::tuple>(unsigned long) vm/vm.hpp:361
    #6 0x557878b47666 in factor::factor_vm::primitive_tuple_boa() vm/tuples.cpp:22
    #7 0x557878b3253d in primitive_tuple_boa vm/primitives.cpp:10
    #8 0x7ffae46bfce0  (<unknown module>)

Address 0x7ffaf54fce70 is a wild pointer.
SUMMARY: AddressSanitizer: stack-buffer-underflow vm/slot_visitor.hpp:130 in factor::slot_visitor<factor::from_tenured_refs_copier>::slot_visitor(factor::factor_vm*, factor::from_tenured_refs_copier)
Shadow bytes around the buggy address:
  0x0fffdea97970: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fffdea97980: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fffdea97990: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fffdea979a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fffdea979b0: 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 00
=>0x0fffdea979c0: f2 f2 f2 f2 f2 f2 00 00 f2 f2 f2 f2 f2 f2[f1]f1
  0x0fffdea979d0: f1 f1 00 f2 f2 f2 f2 f2 f2 f2 00 00 00 00 00 f2
  0x0fffdea979e0: f2 f2 f3 f3 f3 f3 00 00 00 00 00 00 00 00 00 00
  0x0fffdea979f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fffdea97a00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fffdea97a10: 00 00 f1 f1 f1 f1 00 f2 f2 f2 f2 f2 f2 f2 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==17259==ABORTING
```

the lines it refers to are (in order of above appearance)

https://github.com/factor/factor/blob/f976d97983812f073515e5f5466c8dd23f8c0557/vm/slot_visitor.hpp#L126-L130

https://github.com/factor/factor/blob/f976d97983812f073515e5f5466c8dd23f8c0557/vm/aging_collector.cpp#L46-L47

https://github.com/factor/factor/blob/f976d97983812f073515e5f5466c8dd23f8c0557/vm/gc.cpp#L95

https://github.com/factor/factor/blob/f976d97983812f073515e5f5466c8dd23f8c0557/vm/gc.cpp#L149

it would seem that a subtraction was performed on a pointer, which causes a write to a region before the allocated region.

**Comment by erg** [comment]
Dupe of #1886? This issue has better analysis. We could keep both open for now and solve it in this issue.

**Comment by erg** [comment]
Fixed in https://github.com/factor/factor/pull/3139
